### ISSUE TITLE
LuminanceFormat produces "washed out" images, but only sometimes

### ISSUE THREAD

**Issue by tomysshadow** [t0rakka/mango#13]
For my project, one functionality I was hoping for was the ability to load in images as 8-bit grayscale. I saw that mango has LuminanceFormat, and assumed this meant it had the ability to import images as grayscale, and indeed when I tested with a JPEG image, it appeared to work. I'm using the L8 format as defined (but commented) in the format.hpp header, that is:

`mango::image::LuminanceFormat(8, mango::image::Format::UNORM, 8, 0)`

When I decode the following JPEG image, I get a correct looking result, confirming to me that the intent is to convert the image to grayscale.

**Input Image**
![marbles](https://github.com/user-attachments/assets/b22a4940-24ec-445c-8489-d59eef235490)

**Output Image**
![result_good](https://github.com/user-attachments/assets/6d2623cb-24ea-4ef5-85b0-fcf39f644cd2)

If, however, I convert the input image to a PNG of any kind (colour format doesn't matter, I tried 24-bit and 32-bit input) I instead get a result like this.

**Incorrect Output Image**
![result_bad](https://github.com/user-attachments/assets/544d1cfd-c14d-4274-9a8e-6d69882c0db4)

This issue also occurs with JPEG if I use any of the other LuminanceFormat options, for example an AL16 format also causes this failure:
`mango::image::LuminanceFormat(16, mango::image::Format::UNORM, 8, 8)`

Stepping through the code, I can see that this appears to be an issue in the blitter. I eventually end up at the `table_convert_template_unorm_unorm` function, which is OR'ing together all of the colours into the same channel, resulting in a much higher number than should be there. This also happens in the equivalent "template" function - that is, regardless of if a conversion table is supported for the operation or not.

What I would expect to see happen is that the colours are instead averaged to create a luminance value, which is then written into the luminance channel. This ideally could be done separately beforehand somehow to avoid writing a lot of redundant code for every possible format conversion, as this particular operation probably isn't as high priority to be fast.

I would love to be able to use this feature, but since this issue occurs only when the image is not imported "direct" - the conditions for which are fairly complex, different for each format, and may at some point change - and the API does not appear to have any way of communicating when grayscale is not supported for an image back to the caller, I can't confidently use it at the moment. Are there any plans to fix this?

Alternatively I would be fine with using some kind of other hack to do this, for example if it were possible to set the palette to use, I could use a palette of 256 colours just going from #000000, #111111, #222222... #FFFFFF, and that would work fine, if there is any trick like this you can recommend to get grayscale conversion with this library I would be okay with dropping something like that in for this specific scenario.

**Comment by t0rakka** [comment]
This is multi-faceted situation; the Format describes the RGBA, Luminance-alpha or Index channel layout in memory for packed pixels; that's it. The system used to be more complicated and support a lot of things that have been deprecated and killed off over the years.. RGB+A is the main task of the Format. 

The Luminance and Indexed flags are there so that the user has a little bit more information what came out of the files.. for palette files the index used to select colors from the palette, pretty straightforward. Most loaders expand to RGBA anyway, and you have to specifically request indexed decoding. I need this for retro demo coding stuff I do, most people don't care about that it's for me mostly. The indices are always 8 bits even if palette size is only 32 entries, or whatever. Packing the index bits is a hassle I never wanted to solve completely to keep things simpler.. if someone wants to pack the bits more tightly it is possible to do afterwards, of course temporary memory use will be higher.. I don't keep this is a high priority feature it's just so that stuff can get done.

The luminance flag is a bit of a hack there but needed from time to time. The Indexed-to-RGB works because the masks will be identical for RGB.. the trip to other direction requires some weighting scheme like NTSC Luminance Weights and would require a custom blitter. I actually had this a long, long time ago but "simplified" the code to do bare minimum.. it already expands into quite a large chunk of binary code when compiled, kind of nasty. I used to have a JIT compiler that could configure what it was doing to keep the code really compact but only had x86 code generator so it wasn't portable so good riddance. I also played about with LLVM code generation and it has quite a lot of targets but the library is really large so that didn't go anywhere that I would like to develop further.

Long story short: RGB-to-Luminance blitter might come in handy, even if it's super generic and slow as long as the correct color is generated.

OTHER STUFF: sRGB / Linear encoding is detected correctly for many formats but I never tested it super tightly, the goal there is to know the encoding scheme so that images can be used in HDR rendering pipeline correctly. 

I give an example. Formats like JPG and PNG generally (there are many details there) result in decoded image that is in sRGB, or non-linear.. the idea is that the picture is "ready to be displayed" on "averagely calibrated" CRT monitor, think back in 1980's.. you load PNG, do nothing to it.. put into VGA card's framebuffer and it looks "correct" on the monitor. That's non-linear. When doing HDR rendering or workflow you want to know if the image is linear, if so, just use it.. if not.. tell the graphics API that the surface is sRGB so that hardware sampler will return linear values (the encode/decode gamma corrected sRGB is a hardware block in GPUs). Then you keep all your buffers linear, do all calculations in linear space.. and only the resolved buffer is non-linear for the monitor (even LCD/OLED etc monitors are non-linear for legacy reasons). Easiest way is to mark the backbuffer non-linear using mechanism the graphics API of choice exposes, or, have separate resolve shader that does it, whatever. 

So color workflow stuff is little bit considered in the mango image loaders but it requires to use the more complicated API where you get image header from the decoder, then see what you got, make decisions, prepare target surfaces and decode. It's not as easy as just creating Bitmap object.. it's this way so that Bitmap is just container for Surfaces and does not carry any baggage.. in hindsight modern naming conventions have gone a bit differently:  Image and ImageView, or Surface and SurfaceView would fit modern ecosystems better but oh well didn't see into the future. ;)

Back to the issue at hand.. what we need is rgb-to-luminance blitter.. at this time it's deprecated years ago but it could be re-introduced, I guess.. I just hesitating to support all possible bit-depths and permutations .. best solution is to read as 32 bit RGBA and write one routine to do the conversion.. but I see how built-in facilities would be convenient. I'll think about it a little bit we'll see what happens or doesn't. ;)

**Comment by t0rakka** [comment]
This is pretty neat explanation of what you typically would want: 

https://stackoverflow.com/questions/596216/formula-to-determine-perceived-brightness-of-rgb-color

The perceived option 1 from the accepted answer uses this: (0.299*R + 0.587*G + 0.114*B), that is the classic NTSC -way to do it most expect to occur. For speed this is done in fixed-point integers, sum of weights often being 256 so that can scale back with /256, which is shift-right-by-8 (result >> 8)..

**Comment by t0rakka** [comment]
Also, if you read the answers you quickly notice the formula is meant for linear values, so a correct conversion would have to

- know if the image is linear or not
- convert to linear in case it wasn't
- do the luminance calculation
- convert back to non-linear if it wasn't linear originally to retain the encoding

If we want to do this *correctly* it's simpler that the user knows what he wants rather than let us write N permutations "just in case", now I hope it makes more sense why I sweep the problem under the rug. :D

**Comment by t0rakka** [comment]
That said, I'm perfectly at ease just assuming the data is linear and leave it to the caller to do the pre- and post-processing, but then it's not very convenient anymore..

**Comment by t0rakka** [comment]
Also neat things.. GL, D3D, Metal, Vulkan etc.. do these  R8, R8G8 -like formats, which map perfectly to our channel mask scheme.. they convert to other masked formats just fine. The problem of LUMINANCE is that it's not R, G or B.. so the masks are identical so that READING off the format produces "correct" R, G and B values.. it does because it reads them from the same location! =)

Other way around requires the weighted-scheme sleight-of-hand yes-we-are-linear trick. =)

**Comment by t0rakka** [comment]
Let's keep issue open until I figure out if want to throw exception or handle it, I think user should at least know it wasn't supported. ;)

**Comment by tomysshadow** [comment]
libpng has a nice trick where it will just read in the red channel (on the assumption the image is grayscale, so all channels are the same) but can be made to either return early or return an indicator if it encountered a pixel where the green/blue channels did not match, maybe it could be done similar to this. For the meantime I will just read in as RGBA/BGRA and convert it myself until this is supported

**Comment by t0rakka** [comment]
Added detection for unsupported conversions. I think the RGB to Luminance is doable; I just do generic converter and then RGBA to L8 optimized one so that it doesn't suck off the bat.

**Comment by tomysshadow** [comment]
Just wanted to note that I've finished writing a grayscale conversion function for my own program (which also takes into account imageHeader.linear, applies sRGB conversion as necessary) - so this is no longer a high priority for me, though I'll still update mango at some point to see if I can take advantage of this new feature that detects unsupported conversions, so that maybe the image can be read in directly in some limited cases

**Comment by t0rakka** [comment]
Thank you for taking the time to report this and patience. I think it's good to do in your end for now as the scope is much simpler, on my end I would have to handle UNORM, FP16, FP32, FP64, different sizes (8, 16, 32, 64 and 128 bit pixels) and so many permutations which is the reason I deprecated it in the first place. Next time someone runs into this they get exception and know what's going on so that's a step into the right direction. I started implementing it again but it escalated quickly..

There is alternative: I have the color quantization code there that makes some assumptions about the input (RGBA 32 bit, output is always 256 color INDEX8). The grayscale conversion could fit within similar helper function category which has more limited scope of how it works. I think I actually now want that. The Format still indicates it's LUMINANCE format. the only thing that is uncool the blitter is a bit limited and user has to do extra step manually to get the data he wants.

Another thing is might want to detect LUMINANCE in some of the image encoders to get benefit of smaller output files. You got me thinking about this that's great, so thank you again and let's not close this until I taken some steps to improve situation.

**Comment by t0rakka** [comment]
I added LuminanceBitmap helper class; you can pass any surface to it and it allocates the storage and does the luminance calculations. It supports both linear and non-linear encoding. I added similar helper class for the color quantizer so it's nicer to use as well. Any format input is accepted but it internally converts to 32 bit RGBA if needed. The grayscale code isn't super crap I guess, but this allows to add SIMD optimizations without touching the API.

The commit includes example usage in the image_encoder, which now has "--luminance" option. I think we made some progress here so closing this even though we don't do 16 bit or float luminance. =/

**Comment by tomysshadow** [comment]
This is nearly perfect, I can basically slot this in where I had written my own function, though if I may suggest a slight tweak, it would be nice if I could use it to grayscale a PNG without dropping alpha, and since LuminanceFormat supports alpha it would likely not be hard to modify to accommodate this. I've not tested this code so I may have the endianness backwards, but something along the lines of:

```
// notice the new alpha argument
LuminanceBitmap::LuminanceBitmap(Surface source, bool alpha, bool linear)
        : Bitmap(source.width, source.height, alpha ? LuminanceFormat(16, 0x00ff, 0xff00) : LuminanceFormat(8, 0xff, 0))
    {
        size_t bytes = format.bytes();
```

and then later...

```
                const u8* s = source.address(0, y);
                u8* d = address(0, y * bytes);
                for (int x = 0; x < source.width; ++x)
                {
                    u32 r = s[0];
                    u32 g = s[1];
                    u32 b = s[2];
                    u32 v = (r * 77 + g * 150 + b * 29) >> 8;
                    d[x + alpha] = s[3]; // <-- write alpha if enabled, otherwise gets overwritten with luminance
                    d[x] = u8(v);
                    s += 4;
                }
```

**Comment by t0rakka** [comment]
Added support for alpha pass-through. I couldn't make myself to have the if (alpha) in the inner loop, and since I had 4 different loops made them into functions. Bonus feature is that GCC seems to vectorize this; I get SSE2 SIMD code generated with x86_64 without the branch so GCC enjoyers will get a bit of extra speed. I was thinking if someone might want alpha and was like, naah.. and then immediately someone wanted alpha.. 🥇

**Comment by tomysshadow** [comment]
Thank you very much for all of your assistance. I will try it out and see if it works! 👍
