### ISSUE TITLE
Image encoding requires period in extension, but image decoding does not

### ISSUE THREAD

**Issue by tomysshadow** [t0rakka/mango#14]
This is the last thing from me (for now, anyway) as I basically have everything working as I want. This is just a minor thing I ran into that I suspect will be a quick n' easy fix, so I figured I'd make a note of it. Specifically, either of the following codes work:

```
mango::image::ImageDecoder imageDecoder(mango::ConstMemory(address, size), ".jpg"); // works
mango::image::ImageDecoder imageDecoder(mango::ConstMemory(address, size), "jpg"); // also works
```

However, only one of the following codes work:

```
mango::image::ImageEncodeStatus status = surface.save(stream, ".jpg"); // works
mango::image::ImageEncodeStatus status = surface.save(stream, "jpg"); // does not work, "not an encoder"
```

In my case I want to read images already in memory, which I understand undoes some of mango's filesystem related optimizations but that's the situation I'm in. So I had just defined the extensions as some string constants, initially without the period - it's not documented either way if there should be one so I kind of just assumed there shouldn't - but once I discovered this didn't work with encoding, I pivoted to including it everywhere.

It should probably be standardized upon to either always reject the extension without a period, or always allow it, so that this (IMO pretty reasonable) behaviour is not seemingly undefined. I would lean more towards allowing the period to be omitted personally because that way if you happen to have the extension already without a period you don't have to do a string concatenation of the period character, and it's also what std::filesystem uses (not that I know why you'd be using it with mango since it can read the files directly, but it's good to take inspiration from standardized stuff) but it doesn't really matter which it is. Just figured I'd mention it since it feels very much like an unintentional bug.

**Comment by t0rakka** [comment]
Loading things from memory is fine, it doesn't really "skip" any filesystem optimizations at all.. it's the other way around: always load from memory, the filesystem just backs up that scheme. In some systems it's actually faster to read into temp buffer and decode from there! It's just the way these fit together. 

The real background story is that almost everywhere you have "streaming" interface like FILE* where you read, write, seek. I don't want to support both for everything that would be nuts, so when time came to choose one I picked the memory-mapping way as it interacts nicely with more recent hardware. The only practical downside is that 32 bit systems are a bit handicapped with large files; if you only have 4 GB of address space you can't map anything substantial with it.. the process address space is fragmented already to find large enough continuous hole.. with 64 bit this problem disappears.

About the file extension debacle, the idea was originally that "." is always required but seems non-dot also works in some places; oops. But that's a great thing to find out as for encoder/decoder identification we probably want both to work. I'll check everything else as well, like container detection (zip, rar, ..) so that it works the same way.

Let's see what happens.. :)

**Comment by t0rakka** [comment]
Oh yes, I see what happened; the ImageDecoder identifies the decoder first from the memory you give it for decoding..  look what getImageFormatExtension() function does.. if it fails to identify the format then it trusts the filename or extension passed by the user and works the same way the ImageEncoder.

**Comment by t0rakka** [comment]
.. and there is always a reason for things.. it's frustrating that some time you have a "jpg" file that turns out to the png file once you look at it with hex editor. I got fed up with this crap and do what Bill Gates would do, on Windows if you rename .jpg into .png or vice-versa it will still work as it looks like they just look at the header: oh it's IMAGE file let's look what's in it. So I do the same and a lot of headaches went away.. nuts..

**Comment by t0rakka** [comment]
OK, done: now both ".extension" and "extension" work. If the filename didn't have extension, the filename to extension mapping function adds the dot in front of the filename behind the scenes (we assume filename IS the extension since it lacked one). String building shenanigans like this aren't that optimal but it's not in any critical path so we're fine, can always make it better if ever find out it's a bottleneck (we won't).

**Comment by t0rakka** [comment]
OK, done: now both ".extension" and "extension" work. If the filename didn't have extension, the filename to extension mapping function adds the dot in front of the filename behind the scenes (we assume filename IS the extension since it lacked one). String building shenanigans like this aren't that optimal but it's not in any critical path so we're fine, can always make it better if ever find out it's a bottleneck (spoiler: we won't).

**Comment by tomysshadow** [comment]
I see. So basically it was just the behaviour for an unrecognized extension, it makes sense now.

btw, I think you might've missed it since the issue is closed now (I probably should have just made a pull request - still can if you want, to save you the trouble of writing it out and testing it) but could you also provide your thoughts on https://github.com/t0rakka/mango/issues/13#issuecomment-2423183723_ ? I think it would be a pretty easy change and very useful

**Comment by t0rakka** [comment]
That's a good idea, I'll update the code.
