### ISSUE TITLE
Image Proces

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#21]
hello, I want to rotate an image. Can Mango's Bitmap support it?

**Comment by t0rakka** [comment]
Such stuff is better done with GPUs. There are a few functions to mirror horizontally and vertically but don't really use them anymore (I pack textures in atlases and have offset/scale per texture to adjust texcoords depending on where the image is at in the atlas). Mirroring is "free" with such approach so the loading-time mirroring is not used that much. The most used mirroring is y-flip to switch between top-origin and bottom-origin conventions (OpenGL, ES, Metal, Direct3D, etc. use different conventions, right?).

The y-flip is actually easier to do by having a negative stride for a surface and setting the address to bottom-left corner; the just decode or blit into that surface. 

So.. there are many ways to achieve the same result. Completely arbitrary rotation (and scale) are not that complicated to implement but there are so many variations and permutations that I rather not try to implement everything. A little bit on the topic, I did write a software rasterizer recently (2 years ago) to give the SIMD code a little trials:

https://t0rakka.silvrback.com/software-rasterizer

It's a bit more than just rotating a picture, I'm afraid. The texture samplers only support linear memory layout in that prototype. I never implemented tiled memory layout, which is kind of trivial, actually but requires a bit of arithmetic when writing into the texture memory. Same goes for reading but it's quite cheap, just didn't get around to doing it yet. The idea with that is to improve cache utilization and local hit rate to keep performance more consistent regardless of texture orientation. Interesting topic, probably will write a small blog post to give some details and timing results.

For some reason my suspicion is that what you want the rotation for is one-shot kind of situation where you load image, rotate it, and save again. In this kind of scenario the fancy cache optimizations just slow down the overall process since the in-front cost / overhead is more than the saving for doing the operation just once. If you decide to implement the rotation yourself a good advice is that you don't want to do sin/cos more than once. Notice that the offset change to next pixel (x + 1) is a constant, same for (y + 1).. so your inner loop should have two additions and bitwise-and operations:

x' = (x >> n) & xmask
y' = (y >> n) & ymask
x += xdelta
y += ydelta
offset = y * stride + x

Something like that. You can get rid of the shift operations if you have the significant bits at the right positions:

x' = x  & xmask
y' = y & ymask
x += xdelta
y += ydelta
offset = y * stride * x

If your image is power-of-two size, you can also get rid of the multiplication.. simply have the y coordinate shifted to the right position in advance:

x' = x & xmask
y' = y & ymask
offset = y | x
x += xdelta
y += ydelta

BOOM! Very low-cost linear-memory-layout bitmap rotate + scale. I used to do these things with 7 MHz 68k processor in 1990's so with modern CPU you can afford a lot more stuff, but the core loop could be that simple if you are just point sampling (aka. nearest-neighbour). 

A bit of detail about the position of stuff in a register, let's take a look at 16.16 x coordinate:

XXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxx

X = integer part
y = fractional part

To get integer part, you do  coord >> 16, so only X's are left..   y works the same way, but.. let's say, you have 256x256 texture, so:

offset = YYYYYYYYXXXXXXXX

This means, you will have the Y in register like this:

yyyyyyyyYYYYYYYYYYYYYYYYyyyyyyyy
00000000111111111111111100000000  <-- the mask to extract Y

Now you can bitwise-OR the Y into the offset.. and X will be:

XXXXXXXXxxxxxxxxxxxxxxxXXXXXXXX

Notice how X rolls around.. when you do  value += value in C/C++, the values will wrap around just fine.. so you can just mask the bits you need. Hope this helps. :)
