### ISSUE TITLE
Android Development.

### ISSUE THREAD

**Issue by gitindro** [t0rakka/mango#25]
First of all thanks for this **fantastic** framework, mango looks very promising. I've just started development with mango on windows, wanted to know what is the typical workflow for android development.

**Comment by t0rakka** [comment]
The android window/OpenGL support is a bit.. crap, as on Android so far it has been used for lower-level stuff and the Windowing code comes from "elsewhere", but I do have NDK, Android SDK, adb etc. tool-chains which I use daily so I could take a stab at better support eventually. The other code works as-is and gives a nice boost when applied where needed.

The workflow is that I mostly integrate the code with other C++/NDK stuff and interact with Java in as few places as possible (= keeping the talking to each other at minimum). The zip format is almost carbon copy of APK format so the zip container code can be used to interact with apk's internal data. I need to upgrade the code with small changes needed to make it happen in master branch, the code is only in internal branches which are not pushed.. yet.. 

The three platforms where code works interchangeably are: Linux, Windows and macOS. Android build is just for the low-level services for now.. =(

The reason is mostly EGL related, the context creation is a bit messy on GLES.. need to make a nice way to pick which version to create: 1.1, 2.0, 3.0, 3.1, 3.2 .. and make difference between building GLES or GL, for example, NV drivers has these GLES extensions that you can create EGL/GLES compatible context on Windows and Linux when you want to develop GLES stuff on desktop. It's just a mess I didn't want to go into as haven't needed that yet (as mentioned above, the GLES stuff on Android comes from Java side.. and so, things get a bit convoluted..)

It's solvable with but not with generic one-size-fits-everyone way. If you have any ideas I am usually receptive. ;-)

**Comment by gitindro** [comment]
Thanks for the detailed reply. I can understand the whole circus around gles context, I already have gles setup done in android studio, I'll see how can I use mango with it.

**Comment by t0rakka** [comment]
Added support for Android NDK containers:
https://github.com/t0rakka/mango/commit/c87dd813b5fbdfbda6fda641250bf3755ba5915b

This was a massive project but I pulled it off. :)

**Comment by t0rakka** [comment]
Looked into this. The Window comes from Java, so having the current API where the window creation is done from the C++ side would call Java, which would callback to C++ for the events. That doesn't sit very well with how most Android apps are prefer it. It would make porting mango-flavored GL apps a snap of fingers, but probably not what users generally want.. the GL context creation is mostly convenience for myself and most apps probably want to do those things themselves anyway. Not sure if I should complete the work at this time... closing the issue as I think the questions were addressed already. :)
