### ISSUE TITLE
AES decrypt failed

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#26]
Hello, I recently used Mango's AES128 encryption, but why did some content encryption fail to decrypt? The two files result1.json and result2.json are of different sizes. My code is as follows:
Json::Value val, root;
	root["csrq"] = "19800101";
	root["desc"] = "比对失败";
	root["gmsfhm"] = "710104198801011995";
	root["hjdz"] = "498";
	root["mz"] = "710104198801011995";
	root["name"] = "710104198801011995";
	root["qfjg"] = "浦东新区";
	root["result"] = 1;
	root["similary"] = 0.9959377050399780;
	root["status"] = 0;
	root["tasktype"] = 0;
	root["xb"] = "1";
	root["yxqx"] = "20100202-20290909";
	root["image"] = "";

	{//encrypt
		unsigned char sKey128[16] = { 0x76, 0xD3, 0x05, 0xFB,
			0x3B, 0x8F, 0x41, 0xBF,
			0x37, 0x29, 0xB1, 0xC3,
			0x48, 0xCD, 0xA3, 0x1A };
		mango::AES aes(sKey128, 128);
		string strValue = root.toStyledString();
		ofstream of1("result1.json");
		of1.write(strValue.c_str(), strValue.size());
		of1.close();
		std::vector<unsigned char> vOutput(strValue.size());
		aes.ecb_encrypt(vOutput.data(), (unsigned char*)strValue.c_str(), strValue.length());
		string strEnrcypt = "";
		strEnrcypt.assign(vOutput.begin(), vOutput.end());

		//decrypt
		std::vector<unsigned char> vInput;
		vInput.assign(strEnrcypt.begin(), strEnrcypt.end());
		std::vector<char> vDecrypt(vOutput.size());
		aes.ecb_decrypt((unsigned char*)vDecrypt.data(), vInput.data(), vInput.size());
		string strResult;
		strResult.assign(vDecrypt.data(), vDecrypt.size());
		printf("%s", strResult.c_str());
		ofstream of2("result2.json");
		of2.write(strResult.c_str(), strResult.size());
		of2.close();
	}
	getchar();

**Comment by t0rakka** [comment]
My guess is that utf8 encoding uses variable-length symbols for Chinese
glyphs. Length returns length in characters not in bytes.

**Comment by w136111526** [comment]
I've tried converting multibytes to utf8 and encrypting them, but the last part of the decryption is scrambled and everything else works, JSON file can't be parsed,What is the reason? Is the length wrong when I decrypt it?：
{
   "csrq" : "1980-09-28",
   "desc" : "比对失败",
   "gmsfhm" : "710104198801011995",
   "hjdz" : "498",
   "mz" : "710104198801011995",
   "name" : "710104198801011995",
   "qfjg" : "浦东新区",
   "result" : 1,
   "similary" : 0.250,
   "status" : 0,
   "tasktype" : 0,
   "xb" : "男",
   "yxqx" : "20100202?2Ui?K??????

**Comment by t0rakka** [comment]
You must use string::size (returns length of string in bytes) instead of string::length, which returns string length in characters. The end is corrupted which tells me that you have not encoded/decoded all of the BYTES of the string. And with VL-encoding indeed the BYTES should be larger value than string length in characters.

**Comment by t0rakka** [comment]
print the string length in bytes before encoding. How many bytes are you encoding and decoding? Print those values as well. If they are not identical handle that first and we'll see if there are any problems left.

**Comment by w136111526** [comment]
mango::AES aes(sKey128, 128);
		string strValue = root.toStyledString();
		ofstream of1("e:/result1.json");
		of1.write(strValue.c_str(), strValue.size());
		of1.close();
		int nLenMuti = strValue.size();
		string strUtf8 = CPsUtility::MByte2Utf8(strValue.c_str());
		std::vector<unsigned char> vOutput(strUtf8.size());
		int nSize = strUtf8.size();
		int nLen = strUtf8.length();
		aes.ecb_encrypt(vOutput.data(), (unsigned char*)strUtf8.c_str(), strUtf8.length());
		string strEnrcypt = "";
		strEnrcypt.assign(vOutput.begin(), vOutput.end());

nLenMuti is 359, nSize and nLen is 380, Do you need 16 bits for input characters?

**Comment by t0rakka** [comment]
https://crypto.stackexchange.com/questions/8121/aes-plaintext-is-smaller-than-128-bits-how-to-expand

Here are few padding methods, which one to choose depends.. so I didn't want to make the decision for the caller (it's left for you to decide)

https://en.wikipedia.org/wiki/Padding_(cryptography)

I could have done zero-padding easily enough, and filled a temporary block at the end so that arbitrary length inputs and outputs would be easier to deal with. Now that I think of it, I could zero pad when the input is not multiple of 16 bytes (128 bits). When the caller wants to decide the padding strategy he can do it himself and send 16 byte aligned inputs so that I don't touch the data. That would give both approaches simultaneously with the same API. But I need to add some NOTE's in the header so that it's clear what is going on. :)

Would that work for you?

**Comment by t0rakka** [comment]
Regarding the length differences: no, you don't need any padding. Just encode the raw bytes. The utf8 encoding will be fully preserved. It's just encoding scheme. I need to make the AES interface easier to use with lengths that are not multiple of 128 bits (see above). It has never been an issue for me since I 'knew' this instinctively but in hindsight it's a bit awkward to use even if you know about the limitation.

I will implement the automatic zero-padding immediately, after all, my API advertises that the length is arbitrary byte count and doesn't even assert on length % 16. So the block cryptor will clip the inputs correctly soon. :)

**Comment by t0rakka** [comment]
I can safely only handle ECB with above technique as the IV is progressive from block-to-block. I would have to use it's current state with the last block. For now, only the ECB will have the padding assist. It's possible to auto pad every algorithm but for now I'm going wit this.

The ECB is the least secure anyway.. the tricky part is to manage the decryption key in secure manner. Security is difficult.. I consider my code only obfuscation layer security-wise, because it's more than just shuffling bits around. One could easily make a life-time job learning *everything* about the topic and still not be secure enough. :)  It's pretty nuts, how security people want code to run in constant time, etc. so that they don't leak information to the attacker. I know the basics like why salting is a good idea and so on, but when we get into the details, totally n00b and untrustworthy. ;----)

SO; as long as you keep your key secure one way or another (outside of the scope of this simple block encryption engine) you should be in fairly good shape. It could be a bit tricky since in executable that wants to access specific file, the key must come from *somewhere*. The most secure way is that the user has to input it.. then it is stored only in users memory (in optimum case, hehe) otherwise you must store or derive it some ways and then it can be recovered by some <evil dude>. hehe..

**Comment by t0rakka** [comment]
The updated version is live: https://github.com/t0rakka/mango/commit/a5488d47709ebcaa0f93367056230fb00f4d1c9d

The old API for ECB zero pads automatically, as promised by the header (which now has better indicators how the API works). The old methods are renamed xxx_block_xxx to make it more obvious they assume AES block input.

You can remore the padding, etc.. let me know if have trouble with the new code. Cheers! :)

**Comment by w136111526** [comment]
Thanks, you've help me so much
