### ISSUE TITLE
How can JPEG encoded raw bits(array of uint8) can be decoded using 'MANGO' and save as cv::Mat?

### ISSUE THREAD

**Issue by JeyP4** [t0rakka/mango#27]
Hello
My question is for both grayscale and RGB images.
I have [unsigned char *] that points to a jpeg compressed image buffer.

How image can be decoded and save as "cv::Ptr < cv::Mat >  im = ......................... ;   "

Sorry for any syntax error in my question.

Thank you
-Jai

**Comment by t0rakka** [comment]
You can use the "ImageDecoder(Memory memory, const std::string& filename);" to decode from memory. The second parameter name is a bit misleading, I think it needs to be renamed into "extension" or "format_name" or something more descriptive - it is NOT a filename! Check the examples repository for more coding examples.

Memory memory(ptr, size); // your buffer
ImageDecoder decoder(memory, ".jpg");
ImageHeader header = decoder.header(); // get image information..
Bitmap bitmap(header.width, header.height, header.format); // allocate storage..
decoder.decode(bitmap, nullptr, 0, 0, 0); // decode into the surface (bitmap object above)


The decoding target does not need to be a Bitmap object, it just needs to be a block of memory with some stride (vertical distance to next scanline in bytes). You can do something like this:

std::vector<u8> target(header.width * header.height * header.format.bytes());
decoder.decode(Surface(header.width, header.height, header.format, header.width * header.format.bytes(), target.data());


Same outcome. The can think of the Surface as BitmapView (such class / naming does not exist but that's what it effectively is). Or put other way around, Bitmap is a surface with allocated storage.


Ask away if there are any questions left.

**Comment by t0rakka** [comment]
Renamed the parameter from "filename" to "extension": https://github.com/t0rakka/mango/commit/8d79484a92e29c6677a138e9137d20f7d979e0ba

Filename can still be passed and the lower-case extension will be extracted from it (as it used to work, nothing changed internally). The API could inspect the memory and determine what file format it represents; this works for many formats but some lack identifier information so a more precise identification was needed. The format "name" (= file extension) is what is used to tell what the memory is.

Why we cannot use enumeration? Because the decoder/encoder system is plugin based and can be extended dynamically. So fixed enumeration doesn't work. The other similar choice would have been to use FourCC / 32 bit identifiers but again, some formats do not have fourcc codes allocated for them and didn't want to invent my own system for that. So ended up with string based identification which we use now.

**Comment by t0rakka** [comment]
Then..   cv::Mat(header.width, header.height, CV_8UC4, ptr);
Where ptr is target.data(), bitmap.address<u8>(0, 0) or similar (the address of the image data). The CV_8UC4 must match with the format of your buffer.

MANGO does not require your decoding target buffer to be in a specific format but it is advised to use the format returned by the header() method, which should return the format where decoding is fastest (no format conversion or the conversion is the fastest possible). For example, you can allocate 24 bit buffer and decode 32 bit image into it, but you will lose alpha channel (if you don't define any bits for alpha in the target format). The format does not need to be 8 bits of red, green and blue. It could be 7 bits of red, green and blue and 3 bits for alpha. That would work but I don't know why anyone would want to do that. :)

The 32 bit BGRA and RGBA formats are fastest with the JPEG decoder/encoder, so those are recommended. Even if you don't need alpha (and indeed, the JPEG decoder will fill alpha with 1.0 (0xff in 8 bit UNORM format) you should still use these formats since aligned access to the pixels is more efficient.

Here is example declaration for format:

Format format(32, Format::UNORM, Format::BGRA; 8, 8, 8, 8);

First the number of bits, in this case, 32. The UNORM means the values are interpreted as UNSIGNED-NORMALIZED integers. The BGRA tells in which order the components sizes following will be declared: 8, 8, 8, 8 means 8 bits for BLUE first, then 8 bits for GREEN and so on. 

8 bit UNSIGNED-NORMALIZED value means that 0x00 = 0.0, and 0xff = 1.0 .. the values between these are linearly interpolated. How this translated into intensity on your monitor depends on the COLOR SPACE. The JPEG, PNG and many image formats use non-linear encoding, which is already gamma adjusted for display in a computer monitor, which are often non-linear, like sRGB for example.

Usually computations should be done in linear space but a lot of software doesn't really care about that.. the easiest way to do linear color processing is to do it in 32 bit floats. Nor the fastest, but easiest.. :) There is code to do different sRGB to linear and linear to sRGB conversions in the library and they are (a little bit) optimized with some SIMD support so it's a bit faster than manually doing it.

8 bit sRGB to 8 bit linear conversion is easiest to do with lookup table if you want to keep doing computations in 8 bit precision. If you pass the data to OpenCV then you should already be in good hands in this regard. I don't know if they assume linear or non-linear inputs but that's not really something I can affect anyway. :)

Good luck. :)
