### ISSUE TITLE
Is there an error due to the incompleteness of the picture?

### ISSUE THREAD

**Issue by assertdebug** [t0rakka/mango#34]
Is there an error due to the incompleteness of the picture?
code:
    Memory  memData((u8*)pData,byData.size());
    double start = omp_get_wtime();
    Bitmap   bitmap(memData,".jpg");
    double end = omp_get_wtime();
    printf("decode jpeg take time:%dms\n",int((end - start) * 1000));

    if(bitmap.width <= 0 || bitmap.height <= 0)
    {
        printf("decode jpeg error!\n");
        return 0;
    }

Stack Trace (from fault):
libmango.so+00802581 _ZN4jpeg15huff_decode_mcuEPsPNS_11DecodeStateE+00001141
libmango.so+00772758 _ZN4jpeg6Parser18decodeSequentialMTEv+00000694
libmango.so+00775642 _ZN4jpeg6Parser10processSOSEPhS1_+00001802
libmango.so+00781007 _ZN4jpeg6Parser5parseEN5mango6MemoryEb+00000879
libmango.so+00782333 _ZN4jpeg6Parser6decodeERN5mango7SurfaceE+00000221
libmango.so+00610120
libmango.so+00701023 _ZN5mango6BitmapC1ENS_6MemoryERKSs+00000223

**Comment by t0rakka** [comment]
I need the picture file to check what is going on.

**Comment by t0rakka** [comment]
Any decoding errors that are detected will throw mango::Exception. Detecting out-of-data in middle of the image is trivial, could add check. The very-close-to-end-of-file is more difficult as the MCU's bitstream compression would take a hit. What we could do is to have a slow-check-every-byte decoder for the last few MCUs, that wouldn't cost anything in practise. For now the main use case for the library is importing sanitized data but it's possible to strengthen the code against malicious files and inputs. Make a PR if have any improvement ideas. :)

**Comment by t0rakka** [comment]
About EOI marker; each correct JPEG file should end at EOI marker (0xff, 0xd9). It would be super easy to detect if this is the case to get a basic guarantee that the file is complete (of course, malicious files could still cause incorrect parsing). I intentionally skip this check (commented in the code) because there are a LOT of JPEG files out there written by non-conforming encoders that omit the EOI's and the files wouldn't decode. Such files decode with IJG and other libraries, too, so I try to follow the same guidelines. That's why I effectively ignore the EOI; all it does for us is definitely terowminate the parsing.

I also use this as opportunity to rant: the STUFF bytes drive me nuts. Every 0xff must be followed by 0x00 if it isn't a marker (to make it possible to distinguish markers from actual 0xff data bytes). This is critical feature with RST's since it should be possible to robustly detect them no matter what. Nice in theory but in practise makes decoding a total pain in the ass. :) :)

The easy way to handle this would be to do one pass on input data and filter out the 0x00's and then also know exactly the number of bytes in a range. This kind of design would make it 10x easier to make a robust reader that is harder to overrun buffers but it is so *inefficient* that it makes me very sad (I wrote a prototype of this early-on when the code was young). On the other hand, the buffers would be local and fit in L2, so the worst hit of reading off the storage device / slower main RAM could be averted. Maybe worth a second look at some point.

**Comment by t0rakka** [comment]
Thanks; these will keep me busy for a while. Found one crashing file and need to add YCCK support. I also noticed the CMYK fails on one of the files. Added APP14 marker parsing and read the color transformation already, inching my way slowly to supporting more exotic formats. So far the problem has been that no files -> no support.. this fixed that! :) :) 

I optimized the encoder a bit yesterday; 5-10% speedup on x86 and up to 30% on ARM!!! Next: more NEON code for the encoder, then tackle this ticket to add robustness to the code. Should be quiet again in a few weeks.. for the record, at this time this is a "hobby / for fun" project as I am not actively working for our old company anymore (more like 12 years now..). But keeping the old code (c) to that name as it was originally. I'm doing streaming tech these days and did GPU development before this.. long story.. .let's not go into too much detail.. ;-)

**Comment by t0rakka** [comment]
MultiScan image! Fantastic! I ran it through with debug prints enabled: if I force decoder to stop after first scan, see low-res version.. it will be easy to add multi-scanning, I think.. just cache the values (ala' progressive) and delay the processing until all of the data has arrived. It has been a total pain to find these fixes.. big thanks again for the test streams!!!

**Comment by t0rakka** [comment]
I might even get motivation to add a few features back I had earlier: the thumbnail extraction (either from APP segment or just decoding DC's for 1:8 thumbing). Another feature is progressive rendering in controlled steps. Third is the render-to-texture backend but it's a big ugly as requires inter-op with shaders and we have quite a few APIs to deal with (Metal, Vulkan, OpenGL, DX). Funny story: the reason this code exists was to write OpenCL renderer to test the back-then new API. That's how I got into JPEG reading in the first place... for now it is just code drag racing to squeeze milliseconds off encoding/decoding times FOR FUN!!!!

**Comment by t0rakka** [comment]
MultiScan works now! :)

**Comment by JimBobSquarePants** [comment]
Ah that's all fantastic, So glad that I was able to help! Basing my huffman decoder on your one managed to shave 15% off processing times so I really wanted to give something back. 

It's difficult squeezing real performance out to the decoder just now though with incomplete SIMD support in C#. It's due to land in November though for limited platforms so hopefully I can get closer. (2X slower than libjpegturbo currently for baseline, 1.5X for progressive)

I'll tell you what, even though you're doing this for fun, it's awesome to see someone writing an implementation that is not only blazingly fast but actually readable! I've spent more time than I've enjoyed pouring over the code for libjpeg-turbo etc and this was a breath of fresh air!

**Comment by t0rakka** [comment]
Great to hear that someone enjoys the code! :) Of course I named the Huffman decoding optimization "modern" LMAO.. the trick was that the codes are aligned to the MSB so that I can directly compare the values as the "noise" in the LSB's isn't significant. Another thing I played around was transposing the AC's so that reading / writing is as efficient as possible (SIMD-wise mostly in the iDCT). Then choosing where to zigzag so that the hit is as small as possible. Btw; a tip.. there are SIMD optimized zigzag routines which do it in 8 SIMD registers but haven't managed to fit them anywhere w/o performance net loss due to extra pass. :(

**Comment by t0rakka** [comment]
Added field validation / overflow checks to the parser. 80% of the ill-formed fuzzer files "pass" the parsing and throw exception correctly. I'll keep adding more of these over time so there won't be one big bang where everything is magically cool at once. It'll be more like slow crawl towards robustness. Stay tuned.. :D
