### ISSUE TITLE
Bitmap to opencv Mat

### ISSUE THREAD

**Issue by luqinlive** [t0rakka/mango#36]
Hi,
  I use this code :
                Bitmap bitmap("D:\\IMG_2177.jpg");
		cv::Mat dst(bitmap.height, bitmap.width, CV_8UC3, (uint8_t*)bitmap.image);
		imshow("img1", dst);
   but the image is not correct ,how can i convert bitmap to a cv::Mat, thanks.

**Comment by luqinlive** [comment]
i found the error,add the format solved
Bitmap bitmap("D:\\IMG_2177.jpg", FORMAT_B8G8R8);

**Comment by t0rakka** [comment]
Yup; if you don't specify the format the "best" one (selected by the decoder) is used. You can also have blank surface in specified format and blit() into it (the surface can be ptr to the cv specific object). The terminology used by the library is a bit throw-back from old days..

Translation to mode contemporary naming would be:

mango::Surface ~~ modern::SurfaceView
mango::Bitmap ~~ modern::Surface

In other words, Surface is a generic description of a surface.. and Bitmap is a surface that "owns" the memory. So, if you have some piece of memory, somewhere, in some format that we support you can create a Surface (-view) into it and blit into the surface, so we do format conversions and all that stuff from the source surface into the target surface.

The format system is a bit more generic than what the blitter back-end can support but it is done this way so that at least the user of the library can see what's in it.. even if we can't blit the data out. I recently added some indexed/palette format support stuff.. but the palette information is never associated or carried with the surface; you just know it's indexed data and have to keep track of the palette yourself so that you can resolve the RGBA values, when you need them. I sort of didn't want to support palettes at all and deprecated the support but it's now back in the current Diet Zero Calories -API it is now. :)

Anyways, cool that you figured out how to get it working! :)

**Comment by luqinlive** [comment]
Thank you very much, any plans to support vs2013, because some modern C++11 keywords are not supported in vs2013, such as constexpr,

**Comment by t0rakka** [comment]
I bumped the minimum requirements to C++14 a while back. There are no plans to support older C++ standard versions. On the bright side, I will not be migrating over to C++17 for a few years (at least) as there are still too many issues with it when want broader range of compilers and platforms to be supported. The C++14 is fairly solid baseline for now (ICC, MSVC, GCC and CLANG all support it). It might be a hassle for commercial environments to keep up with the latest and greatest but I think C++14 is reasonable requirement in 2019.. plus, since I am not getting paid or anything for this (just a hobby project, sorry if gave impression this is something more than that) I prioritize on things that I need on my daily tasks. This is based off on a library I maintained and developed as part of my day job, history going back to late 1990's .. now it's just something I can't imagine coding without. :)
