### ISSUE TITLE
webp support？

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#38]
Hello, can mango support WebP image format, including encoding and decoding

**Comment by t0rakka** [comment]
I looked at it few years ago but the library is a bit large to include.. trying to keep this as light-weight as possible. But.. there is a way: libwebp, I could configure the build scripts to detect when libwebp is installed in host system and make the interface available in such case.

For now my goal has been to keep the code self-contained and all external/3rd party libraries are hand-merged so that everything builds w/o warnings and uses same build system (whichever is used at any given time; cmake, android build, visual studio, xcode, make). I been in quite many "build hell" situations in projects I been working on and trying to keep the builds as simple as possible.

So; the optional libwebp build "step" might be a bit difficult on some platforms / tool chains but I'll check this out. Maybe the sources will be merged to mango/external, who knows what happens.

Don't expect immediate response.. might be a while, webp is a bit marginal format at this time and so much code for so small gain.. I have a bit same thoughts about Apple's HEIC but it seems to be getting some traction as it's now iOS internal camera format (?) so expecting to see it starting to push mainstream. I also looked at FLIF a while ago, while it looks technically sound it haven't gotten much tooling support in image editors or haven't really seen any number of files in that format..

Summary: FLIF, HEIC, WEBP - have looked into them, prototyped and played around but no merge into mango has happened yet.. I more likely will attack GPU compressed texture format problem a bit before anything happens with file formats. The main problem is that current compressed texture format API has one preferred decode format and some formats decode into FP16, where the preferred is 32 bit RGBA/BGRA. I'm trying to avoid extra round-trip to FP16 with this arrangement but this "hides" some HDR formats, which isn't cool. Looking into having more control over the processing pipeline for those but it can't get too convoluted.. xD

The animated gif works pretty nicely now, I been actually using it myself in a few places.. so thanks for that feature request a while ago. I also added animated PNG (APNG) support maybe a month ago. It works quite alright but has a few feature gaps I am too lazy to patch. Most files should work OK and the missing features will just render the animation frames wrong, but no crashing or anything vital. I just don't support all "restore" modes.. where some parts of the frame must be restored after rendering current frame. That requires keeping a backup of previous frame and other stuff I will implement after find APNG files that actually USE those features. A bit hard to test the code w/o test files... but in case you want to try it, it should work.. 100% identical API to animated GIF playback. The animated gif example has been updated to latest features. :)

**Comment by xixihao123** [comment]
Hello, I'm using Google's libwebp now, but it's a little tricky to use, so I'm hoping to get mango to support this image and finally parse it like a GIF.

**Comment by t0rakka** [comment]
OK guys.. I will look into this "soon", at minimum can create a plugin (the ImageDecoders can be registered at any time to the runtime). More formats never hurt.. I guess..

**Comment by t0rakka** [comment]
DONE; I use the "simple" encode/decode API. Will switch to more fine-tuned methods later and add some more options to ImageEncodeOptions struct. Didn't do super extensive testing but seems to work with a couple of files I found.. will add animation support later also, for now you can only access the main image. Can encode lossy and lossless (added a new option for configuring that).

If you look at the source/mango/image/image_webp.cpp the fundamentals of the API are strikingly similar; the mapping to libwebp is super trivial.. it'll get more complicated after I add more options. :)

**Comment by t0rakka** [comment]
// lossless encode example..
ImageEncodeOptions opts;
opts.lossless = true;
surface.save("test.webp", opts);

**Comment by xixihao123** [comment]
Thank you. I 'll test it later to see if it works.
