### ISSUE TITLE
Can mango be used with VB6.0 program?

### ISSUE THREAD

**Issue by amoltarte** [t0rakka/mango#44]
Hi!
I've a old but widely used software in VB6.0 (Visual Basic 6.0)
I use ijl15 (Intel JPEG Library) for jpeg compression and decompression in it.
Can I replace ijl15 with mango? (as you wrote its faster than ijl and libjpeg-turbo)
Can you provide me a wrapper and binaries for use on Windows?
Any help would be appreciated.

**Comment by t0rakka** [comment]
Sorry; know nothing about VB. Last time I wrote basic was for SVI-318 (8 bit z80) in 1985.. The code doesn't use less CPU, it uses about same amount as IJG/ljbpeg-turbo just spreads the work more so that the latency / responsiveness is quicker.

I don't even know where one would begin making a VB wrapper/binding. One thing that might work for you is that you wrap the parts you would like to use with COM interface and VB being Microsoft Windows development language you could then call these interfaces from there. Probably not the ideal or best approach but something that I know works when you want something to be callable from any language.

**Comment by amoltarte** [comment]
Yes, I wanted to ask you the same.
Can I make a COM component of Mango in C# and use it in VB6.
If mango faster than libjpeg-turbo.


With Warm Regards,
Amol Tarte,
Project Lead,
Rajdeep InfoTechno Pvt. Ltd.
Visit us at http://it.rajdeepgroup.com

**Comment by t0rakka** [comment]
If you look at amount of processing power required to decode image it is ~ 20% cheaper with mango. If you have 4 core computer with HT enabled, it means your hardware concurrency is 8. This means the library can decode image in 1/8th of the time in ideal conditions because the workload can be distributed to all 8 hardware threads. This requires image with RST markers in it, if you don't have those, then the decoding will be bottlenecked by the Huffman/Arithmetic decoder. The iDCT and color conversion is done in parallel.

If you have a single core computer then the library will be on average 20% faster. If you have more cores, more of those will be used and the decoding time will be reduced but same amount of CPU will be consumed as the same computation is still done -- it's just distributed.

Also, you can load multiple images simultaneously. If you use libjpeg-turbo, you can still load 8 images at the same time in their own threads to increase throughput of your system even if the *-turbo is single-threaded. Same thing with Mango, if you load more images at the same time your will squeeze more power out of your CPU because it is computing instead of idling when there is no work for some core by other means.

I don't know your use case.. if it is just processing as many images as possible, having maximum throughput you will have processing in multiple threads and you are maxing out your CPU usage. In this case mango has only slight edge.

If your use case is to decode images with minimum latency, mango is your ticket as it can be order of magnitude faster, but as mentioned above CPU time will be used. On a 10-core i9 processor I typically load images 15-20 times faster (let's say, if libjpeg loads image in 200 ms, it will be processed in 10-20 ms by mango). But notice that in this case the CPU utilization is 100% on ALL cores while doing it.

Encoding is 100% parallel; it will always be faster as I have full control over it.. on decoding I am limited by what data the file contains. If there are no RTS markers, I cannot decode the RST invervals in isolation but have handle whole file serially in-order. The encoder, however, will split the image into number of chunks it processes completely independently and completely in parallel then just dumps the data to storage media. These files are also RST-enabled, so loading them with the library is very fast compared to *-turbo.

If you just take some random JPEG file, chances it has RST are 1 out of 10 (could be less, or even zero percent odds if all files are generated with a specific encoder but then they are not random files).
