### ISSUE TITLE
scale image

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#51]
can mango use simd to scale images like opencv

**Comment by w136111526** [comment]
How am I supposed to write this

**Comment by t0rakka** [comment]
All CPU image transformation routines were deprecated from the library 10+ years ago; it is more efficient to rotate, scale and so on with a GPU. Just upload the data into a texture and render using graphics hardware. You are not doing software / CPU rendering, I hope? =)

**Comment by t0rakka** [comment]
Hope this helps getting started (but I do not recommend doing this!)

https://gist.github.com/t0rakka/291457e0995725f66655e683f9dd1271

Usage: bicubic <filename.ext> <scale>
Example: ./bicubic test.jpg 40

The scale is how many times smaller the original image is first made (using Area Filter for minification) and then Bicubic filter to scale the image back to original size. The result should be blurry version of the original picture. :)

The code is written so that different filter is used on each x- and y-axis depending on if the image is being enlarged or shrink horizontally and vertically. The reduction/minification filter is a bit overkill, I think, but gives fairly good quality. 

The code is old crap and I wouldn't write it using float filters if I were to do it again today. 100% integer scaling would be much better as it would use SIMD a lot better... but this works, more or less. Pay close attention to sampling point inside the pixels, I think it is top-left corner and not center of the pixel samples so keep that in mind when scaling; the image might be off by 0.5 pixels when you zoom into the image compared to nearest-neighbour filtering but I honestly can't remember, it's been a long time since I wrote this.. :D
