### ISSUE TITLE
Python wrapper for mango

### ISSUE THREAD

**Issue by tonysy** [t0rakka/mango#56]
Hi, do you have any plan to support read image with mango on python, especially for the deep learning community?

**Comment by t0rakka** [comment]
At the moment I am in process of fuzz-testing and hardening the code against incorrect inputs and is a top priority. I am open for pull requests if someone wants to contribute. The (c) in headers is for a company I started in late 1990's and where the library was originally developed. I am currently working for Virelabs (www.virelabs.com) and maintaining the code is just a hobby.. there is no large infrastructure or anything like that, just me and nice people who contribute and report bugs. The code is used in quite a many places but there is no money involved so it's all open source activities.

I use this as opportunity to tell a little bit about the roadmap ahead: the ultimate dream is to port the code to C++20 module system after the compilers and toolchains are mature enough. This will bring in versioning into the library so that it can be approved into distributions, the binary interfaces should be more mature and fixed-in-place by then. The ugly corners of the code will disappear, for example, the C++17 has support for proper memory alignment on the memory allocators so our custom memory alignment mess will disappear. The memory mapping API will use mapping ranges, compression interface needs a facelift for progressive compression and decompression and so on. For now I keep turning up code and the final interfaces will be in the C++20 aka. MANGO2 .. for now it's about making things more reliable (the fuzz testing is part of that).

We will need integration with OpenCL, CUDA and other compute APIs so that we use the available hardware more efficiently. For example, when JPEG decoding target is GPU surface we can do the color conversion from YCbCr with the GPU. Intel CPUs have JPEG encoding/decoding built-in, so we want to be able to use those engines when supported. macOS has APIs for acceleration for JPEG (and other formats) but using them is tricky to be efficient in all  situations. I have prototype code for various platforms and OS'es for using the available hardware - in ideal case we detect and utilise the fastest available means but it's a horrible mess how these things are exposed to the programmers. It's different in every OS, the support is very spotty/random and so on. It's a great shame that we have so much hardware which is never used because there are no coherent APIs to do anything. In the long run I hope that this can be addressed.. but realistically, I think I am not in very good position to solve the problem.. the solution must come from the OS vendors and hardware manufactures, with proper standardisation. But I am looking into it and will do what I can.. we'll see what happens. :)

p.s. thanks for the request & apologies can't do much about it at this time.
