### ISSUE TITLE
Trying to pass the texture loaded to opengl

### ISSUE THREAD

**Issue by Biobots** [t0rakka/mango#59]
After instantiate a bmp object like this:
`mango::Bitmap m(mem, "bmp");`
How can I pass the pointer to OpenGL?

**Comment by t0rakka** [comment]
You might want to make sure the format is 32 bit RGBA or BGRA as well:

mango::Bitmap m(mem, "bmp", mango::Format(32, mango::Format::UNORM, mango::Format::RGBA, 8, 8, 8, 8));

You get the pointer to image from m.image and pass it to OpenGL, there are many ways to do this depending on how you want to do it. The classic one is:

glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, m.width, m.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, m.image);

**Comment by Biobots** [comment]
```cpp
mango::Bitmap m("a.tga", mango::FORMAT_B8G8R8);
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, m.width, m.height, 0, GL_BGR, GL_UNSIGNED_BYTE, m.image);
```
Thanks! Code above works well. However, I would like to embed shaders and images into the final executable file. So I compiled them into binary files via cmake and tried following code which didn't work:
```cpp
extern const char _binary_misc_a_tga_start, _binary_misc_a_tga_end;
std::string str(&_binary_misc_a_tga_start,&_binary_misc_a_tga_end-&_binary_misc_a_tga_start);
mango::Memory mem((unsigned char*)str.c_str(), str.length()*sizeof(char));
mango::Bitmap m(mem, "tga", mango::FORMAT_B8G8R8);
```
Wondering if there's any solution.

**Comment by t0rakka** [comment]
On Windows adding the files as Resources might be the easiest way; there are win32 APIs to get address to resources: FindResource, LoadResource, etc.

**Comment by Biobots** [comment]
Actually embedded shaders work well. Maybe it's better to place resources like images in an external folder. However I'm still wondering how I can make embedded image work since I would like to build a small cross-platform demo with single executable file first.

**Comment by t0rakka** [comment]
You could use bin2obj or similar tool, but those are slightly different for each platform. You can bundle all of the data into a zip, rar or similar container and bin2obj it, then access the container with mango::filesystem::Path object. You can create a Path object from raw memory. I recommend not using compression so that the path will be memory mapped directly to the linked address.

Look into the mango-examples repo how to use filesystem::Path objects.

Or you can create a simple tool to convert the file(s) into a c++ header and include it (which will be quite slow since the header might be quite a large but for small amount of data that should be fine).

This problem is a bit outside of scope for the library, don't you think? =)

**Comment by Biobots** [comment]
I'll try these later. Thanks a lot for providing substantial solutions though my question, like you said, has nothing to do with the library itself. :)

**Comment by Biobots** [comment]
Found where the problem lies. 
```cpp
extern const char _binary_misc_a_tga_start, _binary_misc_a_tga_end;
mango::Memory mem((unsigned char*)(&_binary_misc_a_tga_start), (&_binary_misc_a_tga_end-&_binary_misc_a_tga_start)*sizeof(unsigned char));
mango::Bitmap m(mem, ".tga", mango::FORMAT_B8G8R8);
```
Above works well. It seems that I should use ".tga" as the second parameter instead of "tga" since there should be a "." to split the extension.
