### ISSUE TITLE
Compile error due to missing u8_crc32

### ISSUE THREAD

**Issue by DouglasLivingstone** [t0rakka/mango#60]
Hi! Since a576821e9c56e2fa60d03b03f33855352ac8049a `libmango.so` is failing to build with:

```
~/mango/build/unix$ make -j20 libmango.so

~/mango/source/mango/core/crc32.cpp:810:19: error: ‘u8_crc32’ was not declared in this scope
             crc = u8_crc32(crc, *memory.address++);
                   ^~~~~~~~
```

A quick workaround is:

```diff
diff --git a/build/unix/makefile b/build/unix/makefile
index a92f68d..e392a60 100644
--- a/build/unix/makefile
+++ b/build/unix/makefile
@@ -46,7 +46,7 @@ CPP_STD = -std=c++14
 OPTIONS     = -c -Wall -O3 -ffast-math
 OPTIONS_GCC = -ftree-vectorize
 
-OPTIONS_X86 += -maes -mpclmul
+OPTIONS_X86 += -maes
 
 # linker options after objects (gcc 4.9 workaround)
 LINK_POST =
```

I think the problem is to do with the nesting of `#if` statements in `crc32.cpp`, abbreviated they are:

```
#if defined(MANGO_ENABLE_SSE4_2)
    #if defined(__PCLMUL__)
        #define MANGO_HARDWARE_CRC32
    #endif
#endif

#if !defined(MANGO_HARDWARE_CRC32) || defined(__PCLMUL__)
    #if !defined(__PCLMUL__)
        inline u32 u8_crc32(u32 crc, u8 data) { }
    #endif
#endif

#if defined(MANGO_ENABLE_SSE4_2)
    #if defined(__PCLMUL__)
        inline u32 u8_crc32(u32 crc, u8 data) { }
    #endif
#endif
```

So if `MANGO_ENABLE_SSE4_2` is not defined but `__PCLMUL__` is defined, then neither `u8_crc32` is declared.

**Comment by DouglasLivingstone** [comment]
Nice, much easier to read! I'll be fetching the images over a network, so to get started I'm using:

```
    Memory memory(data, size);
    Bitmap bitmap(memory, ".jpg");
```

Compiling with `make -j20 libmango.so simd=sse4` on `master` works well, so I'll start by experiment with that.

I'm getting a new error with a clean checkout when running without the `simd` flag, `make -j20 libmango.so`:

```
~/mango/source/mango/core/crc32.cpp: In function ‘mango::u32 {anonymous}::u64_crc32(mango::u32, const u8*)’:
~/mango/source/mango/core/crc32.cpp:728:16: error: ‘_mm_extract_epi32’ was not declared in this scope
         return _mm_extract_epi32(xmm_value, 2);
```

I've not used SIMD directly before, so I'm not sure why that would be missing!

**Comment by t0rakka** [comment]
It's a SSE 4.1 instruction; should be available with -msse4.. what compiler?

**Comment by t0rakka** [comment]
It's a SSE4.1 instruction, alrighty, the CLMUL also requires SSE4.1, so the code was correct in that sense to begin with. Well, this time it'll be easy to fix.. i just require both SSE4 and CLMUL. :)

clang has the _mm_extract_epi32 visible even w/o SSE4 flags set but it shouldn't so I missed that one. Fixed in a sec. :P 

Just in case, which compiler you were using so that I can test with it as well.

**Comment by t0rakka** [comment]
Alright fixed.. check how it works for you. 

I had alternate fix option also: the _mm_extract_epi32 can be done using SSE code like this:

        return _mm_cvtsi128_si32(_mm_shuffle_epi32(a, 0xaa));

But this is less efficient. I could have called simd::get_component<2>(reg) so that the fastest code is chosen (SSE or SSE4.1 variant) depending on compiler switches but I chose to force the fastest always for now.. so the CLMUL requires both CLMUL + SSE4 (.1).

Funny thing is you don't even really care about the CRC32 here at all.. this regression came from recently (just a few days ago) adding the CLMUL variant.

NOW IT SHOULD COMPILE... argh...

**Comment by t0rakka** [comment]
Also good to know: leaving the simd empty defaults to SSE2 on x86_64 as it is part of the x64/x86_64 ISA - it is always available on 64 bit x86.

For 32 bit x86 the empty simd defaults to NO SIMD, so simd=SSE2 is recommended as minimum as it is quite old extension by now (available since 2001). Of course, if you are compiling for really old x86's it's still OK to do so but not the best idea in 2020. =^)

It's actually a bit annoying how the SIMD is handled in C++ compilers since you have to enable it, and if you do, compiler is free to use it at any time it wants not just when you are explicitly writing simd code with intrinsics. This is where JIT compiler code shines: it can select best instructions in runtime compilation for clients specific architecture. But we'll work with what we have, right? My approach so far has been compiling multiple dynamic libraries and loading the correct one based off runtime cpu flags.. extra hoops to jump and very annoying.. but it is what it is.. :_(

**Comment by DouglasLivingstone** [comment]
It compiles! Yes, I was wondering which `simd` option was the best, I'll benchmark them and see which runs fastest on my CPU :-) Thanks for the fixes and hints!

**Comment by t0rakka** [comment]
For the JPEG code we have four "levels" for x86:

1. no simd, slowest
2. sse2
3. ssse3  (not a typo. the extra s means "supplemental")
4. sse4.1

Most of the benefit comes from the sse2. ssse3 can't even be enabled by itself, it comes bundled with the -msse4 but there is distinction at the code level between the two. The sse4 adds some faster 24 bit encoding/decoding modes, but if you're not using 24 bit surfaces you mostly shouldn't care about that. SSE2 handles most of the SIMD action just fine, the other levels are little extra I been throwing in there for fun during the years.

At first I was just doing a bit of R&D for upcoming new compute API, OpenCL at work (I used to be graphics engineer at ATi, the graphics card manufacturer). One of the use cases we studied was compute accelerated JPEG decoding, just to get a feel for the new API and what we wanted from the driver and hardware. So that's why I got into the JPEG to begin with.. then years later decided to write a decoder on my own time for fun and this is it pretty much. 

This is 100% done in CPU as you can see.. the GPU / compute acceleration kind of bad idea if have to get the data back from the GPU, this kills the performance gains completely. The bottleneck is Huffman decoding anyway. I always stuck my finger into decoding with the GPU/Compute when the target surface is in GPU like OpenGL texture, or something like that but a good API always failed to materialize.. always some dumb small snag how to make it generic. 

Another idea I been rolling around is using the hw decoding engine in-CPU. Intel for example has in-hardware decoding engine but access to it is awkward.. how dumb is that, there should be open standards to access hardware everyone has. Same thing with cellphones.. most Android phones have hardware engines but access to them is non-trivial (=understatement).

It would be cool, if some day someone makes universal API for this sort of things. Maybe I'll look at it at some point.. but for now it's so painful that CPU decoding is 100x easier. :D
