### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by viniciusfbb** [t0rakka/mango#62]
First I congratulate you for the excellent library, very good work!

Do you plan to implement support for Metal on OSX / iOS?

**Comment by t0rakka** [comment]
Metal is swift / objc, I am not interested writing a bridge code like that. All my iOS code is swift and missing interop is bugging me.. will have to figure out something that lasts.. :(

**Comment by viniciusfbb** [comment]
Thank you very much. I will use the jpeg and png decoder of your lib which are amazing. Do you have any prevision of any improvements using new gpus?

**Comment by t0rakka** [comment]
There would be benefit if the image is decoded into a GPU surface. The bitstream decoding would still happen in the CPU so there would be a bottleneck. It might be possible to use compute for the decoding but I never tried that (yet) but might be a nice R&D project. Not all paths would be accelerated at first since there are so many permutations because the JPEG format is a little bit too flexible for it's own good.

The incoming bitstream is a lot smaller than YCbCr/RGB so getting the data into GPU would be more efficient that way. Something to think about in the future..
