### ISSUE TITLE
Batch jpeg images decdoer from memory

### ISSUE THREAD

**Issue by pkpioneer** [t0rakka/mango#68]
In your JPEG Decoding Benchmark , we can find mango is the fatest jpeg decoder when using batch processing to decode multi jpeg images.  So how can i use mango to do this ? or  Where can i find the interface or call functions  guide for user?THS

**Comment by t0rakka** [comment]
You probably will be I/O limited so keeping the data coming off the storage media should be a priority. On the other hand you might not want to burn too much memory for buffering, and also, consuming the data as quickly as possible improves (cache) locality so you might want to keep this in mind as well. Any custom solution like this depends on the workload and hardware you have.. it is a different story with CD-ROM/DVD over Hard Drive (spinning magnetic media) over SSD (solid state storage).

Rotating media has heavy cost for seeking, especially for optical discs.. for magnetic media the seek is still 5-10 ms, which is .5 to 1% of throughput for every seek. 150 MB/s hard disk can read 1.5 MB of data for every seek.. so you might want to organise your data to minimise seeking overhead. Maybe have only one thread to hit the disk and serialise the reading, then distribute the processing to multiple threads.

This is quite involved topic so there is no one answer that fits every situation. Here's the code used in the article for starting point:

https://github.com/t0rakka/mango-examples/blob/master/jpeg_multithread/jpegtest.cpp

The MMAP approach in the example is generally slower as it does hit the disk pretty randomly and from multiple threads but it's not that bad with solid state storage. Remember that you might not want to use the code verbatim but just view it as one way to get the job done. The point is that you can integrate this code into your own custom pipelines.. before 2012 the earlier version of the code had "streaming" interface with seek+read, which then could be anything.. but generally working with buffers is more efficient. The downside is large buffers may not fit into memory, or at least not in the cache so streaming data in might be better. The MMAP works a bit like this; you can either read the whole file into a buffer or memory map it.. but if you memory map it, the storage system will be hit by multiple threads.. but streaming in multiple streams would suffer from the same problem so.. in the end it was overall best to just work with memory instead of streams.

I still could retrofit the streaming interface but it would be mostly waste of time with modern systems.
