### ISSUE TITLE
JPEG encoder has GPL code that is not affected by MANGO_ENABLE_LICENSE_GPL

### ISSUE THREAD

**Issue by jarnoh** [t0rakka/mango#84]
I can see GPL code disclaimer in jpeg/jpeg_encode.cpp, but the project is always linked against that file, even when the GPL code is not enabled.  This is pretty serious issue, if you don't want to accept GPL license.

In my own branch 19fa31f91f0998274ee262020f9efeaf252f5336, I tried to figure out what parts are covered by GPL and what are standard mango license.  At least the sample type code in jpeg_encode.cpp is also used by decoding, so better solution would probably to move it to own file and set the whole jpeg_encode.cpp to be flagged by `MANGO_ENABLE_LICENSE_GPL`

**Comment by t0rakka** [comment]
The (C) should be deprecated at some point TBH, nearly all of the code is rewritten from scratch. I just started with that original code and now these things are still left:

- the quantization tables
- read_xxx functions

So, if I switch to the qtables from the JPEG Standard those will be non-GPL. The read_xxx need to be rewritten and then the (C) can be dropped. The tables might already be good-to-go stuff, just need to cross reference and check.

I'll keep this issue open until this is resolved either with rewrite or license checking whole file.

**Comment by t0rakka** [comment]
Added comments on the code that the tables are from T.81, Tables K.1 through K.6. The link to the standard is in jpeg.hpp header.

While looking at them, the sizes could be encoded into half the space (they only consume 5 bits per entry, so u8 could be nice storage unit). Back in time I also tried packing the symbol and size into u32 but it was slower that individual tables. I guess MOVZX beats SHR. :D 

While at it, I try some bit-packing and interleaving again if I get better results this time..

The last "nut" to bust is the read_xxx functions which basically just fill the 8x8 MCU with relevant data so that don't have to do clipping and other crap (component swizzle) in the inner loops. There probably is a better way, this just never was a bottleneck.. but now it is a license bottleneck so I'll take a crack at it.

**Comment by t0rakka** [comment]
Added the GPL license guard to the encoder. If I don't have time to rewrite the GPL parts, then the code will be under correct licence. Period.

When I can make the code "free" of political bullshit hassles down the road, I will remove the guard. Thank you sir! 👍

**Comment by t0rakka** [comment]
FYI: tested encoding the symbol sizes into 4 bits as "size - 1" so the sizes were 0..15, about same speed, not worth the hassle of more complicated code. I interleaved the size + symbol, same result, about same speed.

I also tried making the table 16 elements wide instead of 10, so that can use * 16, instead of  *10, which seemed to result two LEAs. No noticeable difference.

Last, transposed the table so that it turned into size * 16 + runLength, that gave around 4% speed bump (I updated the jpeg_benchmark to catch this easier) but only updated one code path so didn't commit this yet.

Why transpose? It has two benefits: 1. can use the *16 w/o making the table larger. 2. the small symbols are closer together in memory so the memory access pattern favours small symbols which are more frequent. 

I'm all over the place currently so let's wrap this up and call it a successful issue close. :D
