### ISSUE TITLE
Does it support image cropping while decoding ?

### ISSUE THREAD

**Issue by kbinias** [t0rakka/mango#85]
Does it library support image cropping while decoding ?
I mean functionality similar to that of libjpeg-turbo, it dramatically speeds up the processing of a portion of the image.

**Comment by t0rakka** [comment]
The question is a bit ambiguous as it could mean multiple things. I assume that you are asking if we can selectively decode only portions of the image selected by "crop rectangle" ?

The JPEG data layout is such that you have to decode complete MCU scans to get the data in the middle. If the file does not have RST then the complete file has to be decoded from the beginning until last MCU of the crop rectangle has been decoded. If the file has RST the decoding can begin from the middle of the file from the first RST before the crop rectangle begins but we still need to seek the RST which means every byte up to that point have to be scanned for "0xff, RSTn" byte-pattern.

The IJG API itself makes it look like you can decode scanline at a time, which is kind of true: internally they have to decode one MCU scan completely and cache it, then return individual scanlines to the caller. If the image is progressive then they must decode complete image and return requested scanlines from the cached image. MANGO does handle encoding differences internally.

Yes; you can decode into a surface which is smaller than the image in the file but this means "crop" is handled in multiple passes which is less efficient as a copy of while image is made. If the decoding target surface is same dimensions (or larger) the decoding is single-pass operation where the decoding is done directly into the target surface; this is the best and most efficient way to go with this library.

No plans to support cropping as requested because the implementation would never be very good because of the format constraints.

**Comment by t0rakka** [comment]
In the future I hope people notice the new "discussions" feature in the main page, please ask questions there.
